FORM_CONFIG,FORM_RENDEX,FORMSENHA,GRID_ESTORNO,GRID_RECEITA,FORM_BATEPAPO,FORM_ADV,FORM_ACOMPA,FORM_PROTOCO,FORM_RECEB,FORM_DARF,REL_EDIF,REL_SOCIOS,REL_CONJ,FORM_ETIQUE,REL_BAIX_SIND,REL_BAIX_CONF,REL_BAIX_MES,REL_OPOSICAO,FORM_INSTRU,BOLETOS_SOC,GUIAS_CONF_AVUL,GUIAS_CONF_ADMS,GUIAS_SIND,GRID_SINDICAL,GRID_CONF,GRID_MENSALIDADE,REL_CONF_P,REL_SIND_P,REL_CON_AD_P,REL_SIND_AD_P,FORM_RETORNO,TESTE_BARRAS,FORM_EMAIL_CONT,FORM_ADM,FORM_ASOC,FORM_CATEG,CAD_CURSOS,CAD_OPOS,FORM_FENATEC,FORM_RUA_GRU,FORM_CNPJ,CADATENDI_SOC,FORM_LIS_SIND,FORM_LIS_SOC,FORM_EDIF,CADASTRO,FORM_DENUN,FORM_SEND,FORM_JORN,FORM_VAGAS,APOSENT_1,FORM_ODONTO,FORM_TIETE,FORM_MANUT,FORM_FOTOS2,GRID_DEBITO,FORM_MENSALIDADE,FORM_SERVS,FORM_RECEITA,FORM_SAUDE,REL_SOC_DIA,BAIRRO_RUA,CRACHA_1,REL_ADMS,NOTICIAS,NOTICIAS2,NOTICIAS3,NOTICIAS4,FORM_ETIQUE1,FORM_ETIQUE2,FORM_ETIQUE3,FORM_ETIQUE4,EMAIL_BOLETIM,BOLETIM,


CREATE TABLE `permissoes` (
  `id` int(11) NOT NULL auto_increment,
  `login` varchar(30) NOT NULL,
  `tabela` varchar(50) NOT NULL,
  `incluir` varchar(3) default NULL,
  `alterar` varchar(3) default NULL,
  `excluir` varchar(3) default NULL,
  `imprimir` varchar(3) default NULL,
  PRIMARY KEY  (`id`)
);

-- 
-- Extraindo dados da tabela `permissoes`
-- 

INSERT INTO `permissoes` VALUES (12, 'LOARD', 'TT_SER_01', 'SIM', 'SIM', 'NAO', 'SIM');
INSERT INTO `permissoes` VALUES (11, 'LOARD', 'SOCIOS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (4, 'ADRIANA', 'SOCIOS', 'SIM', 'SIM', 'NAO', 'NAO');
INSERT INTO `permissoes` VALUES (23, 'LOARD', 'ADMS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (10, 'LOARD', 'EDIFICIOS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (7, 'ADRIANA', 'CAIXA', 'SIM', 'SIM', 'NAO', 'SIM');
INSERT INTO `permissoes` VALUES (13, 'LOARD', 'CURSOS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (14, 'LOARD', 'ODONTOLOGICO', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (15, 'LOARD', 'DENTISTA', 'SIM', 'SIM', 'NAO', 'NAO');
INSERT INTO `permissoes` VALUES (16, 'CLEUSA', 'SOCIOS', 'NAO', 'NAO', 'NAO', 'NAO');
INSERT INTO `permissoes` VALUES (17, 'LOARD', 'APOSENTADOS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (18, 'LOARD', 'CLUBE_TIETE', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (19, 'VALDECIR', 'CLUBE_TIETE', 'SIM', 'SIM', '', 'SIM');
INSERT INTO `permissoes` VALUES (20, 'LOARD', 'ABERTO_SOC_TIETE', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (25, 'LOARD', 'VAGA', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (24, 'LOARD', 'OPOSICAO3', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (26, 'LOARD', 'LISTA_LOARD', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (27, 'LOARD', 'INSTRUCAO', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (28, 'LOARD', 'ATENDIMENTO_SOC', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (29, 'LOARD', 'LIS_FUN_SIND', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (30, 'LUCIANO', 'EDIFICIOS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (31, 'LOARD', 'DEBITO', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (32, 'LOARD', 'CONF', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (33, 'LOARD', 'SAUDE_ATENDI', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (34, 'LOARD', 'GRUP_LIS_BAI', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (35, 'LOARD', 'CRACHA', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (36, 'LOARD', 'NOTICIAS', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (37, 'LOARD', 'GERADOR_CONF', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (38, 'LOARD', 'NOTICIAS2', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (39, 'LOARD', 'NOTICIAS3', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (40, 'LOARD', 'NOTICIAS4', 'SIM', 'SIM', 'SIM', 'SIM');
INSERT INTO `permissoes` VALUES (41, 'LOARD', 'EMAIL_BOLETIM', 'SIM', 'SIM', 'SIM', 'SIM');